using Test
include("test_basic.jl")
include("test_eval.jl")
include("test_tree.jl")
include("test_infoset.jl")
include("test_infoset_manager.jl")
include("test_cfr.jl")
include("test_cfr_traversal.jl")
include("test_terminal_evaluation.jl")
include("test_cfr_stopping.jl")
include("test_monte_carlo_cfr.jl")
include("test_tree_validation.jl")
include("test_tree_traversal.jl")
include("test_tree_memory.jl")
include("test_advanced_isomorphism.jl")
